### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by micahaza** [gordonpace/contractLarva#1]
:~/projects/contractLarva/src$ /opt/ghc/bin/ghc -o contractLarva Main.hs 
[ 1 of 10] Compiling Parseable        ( Parseable.hs, Parseable.o )

Parseable.hs:18:1: error:
    Could not find module ‘Text.Parsec’
    Use -v to see a list of the files searched for.
   |
18 | import Text.Parsec
   | ^^^^^^^^^^^^^^^^^^

Parseable.hs:19:1: error:
    Could not find module ‘Text.Parsec.String’
    Use -v to see a list of the files searched for.
   |
19 | import Text.Parsec.String
   | ^^^^^^^^^^^^^^^^^^^^^^^^^

**The Glorious Glasgow Haskell Compilation System, version 8.2.2**

**Comment by joshuaellul** [comment]
Did you try installing parsec:
cabal install parsec

This thread might help:
https://stackoverflow.com/questions/9058914/cant-find-parsec-modules-in-ghci

**Comment by micahaza** [comment]
I don't have cabal on my machine. Would be nice to have a bit of wiki page about installation. Thanks for the quick reply.

**Comment by gordonpace** [comment]
In that case, the easiest option is to install the Haskell Platform on your machine, which comes with Parsec included: https://www.haskell.org/platform/

We'll change the README file to reflect this.
