### ISSUE TITLE
Getting error "Variable not in scope" compiling

### ISSUE THREAD

**Issue by Ture2** [gordonpace/contractLarva#6]
Hi, I'm just trying to compile the tool and I'm getting this error.
![Captura de pantalla 2019-12-28 a las 17 55 59](https://user-images.githubusercontent.com/22908515/71547025-8cf8b280-299b-11ea-8d76-f9715f597515.png)

I don't know anything about Haskell so I'm not enabled to fix this.

**Comment by shaunazzopardi** [comment]
Hey,

The `fromRight` function is a function from the [Data.Either package](http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Either.html). You may not have all the required packages installed. If you installed the [Haskell Platform](https://www.haskell.org/platform/) this shouldn't be a problem, so I guess you simply installed GHC on its own. 

The simplest solution is to just install the [Haskell Platform](https://www.haskell.org/platform/). Let me know how it goes.

**Comment by Ture2** [comment]
Hi,

Your answer was right, the problem comes with my OS. I'm using Ubuntu and the default version installation using sudo apt-get install is 8.0.4 which hasn't the package.
If someone needs, to avoid this error the solution I found was install with the following command:  $curl https://get-ghcup.haskell.org -sSf | sh

Thanks so much !
